version: "3"

networks:
  payment:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'payment'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      TZ: 'America/Sao_Paulo'
    networks:
      - payment
    ports:
      - 3306:3306
    expose:
      - 3306

  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    volumes:
      - .:/opt/payment
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - payment
    ports:
      - 80:80
    depends_on:
      - mysql
    command: ./docker/entrypoint.sh
